import type { Metadata } from "next";
import "./globals.css";
import Navbar from "@/components/Navbar";
import Footer from "@/components/Footer";
import Providers from "./providers";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`antialiased`} cz-shortcut-listen="true">
        <Providers>
          <Navbar />
          <main className="relative overflow-hidden">{children}</main>
          <Footer />
        </Providers>
      </body>
    </html>
  );
}
